local settings = {
    -- every line should be same width without escaped \
    header = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            "",
            "",
            "",
            "",
            "",
            "",
            " ██╗    ██╗ ██████╗ ███╗   ███╗██╗   ██╗██╗███╗   ███╗",
            " ██║    ██║██╔═══██╗████╗ ████║██║   ██║██║████╗ ████║",
            " ██║ █╗ ██║██║   ██║██╔████╔██║██║   ██║██║██╔████╔██║",
            " ██║███╗██║██║   ██║██║╚██╔╝██║╚██╗ ██╔╝██║██║╚██╔╝██║",
            " ╚███╔███╔╝╚██████╔╝██║ ╚═╝ ██║ ╚████╔╝ ██║██║ ╚═╝ ██║",
            " ╚══╝╚══╝  ╚═════╝ ╚═╝     ╚═╝  ╚═══╝  ╚═╝╚═╝     ╚═╝",
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },
    -- name which will be displayed and command
    body = {
        type="text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
            "  Find File        <leader>+ff",
            "",
            "  Find Word        <leader>+fs",
            "",
            "󰈞  File Explorer    <leader>+ee",
            "",
            "  Colorschemes     <leader>+cs",
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
    },

    -- body = {
    --     type = "mapping",
    --     oldfiles_directory = false,
    --     align = "center",
    --     fold_section = false,
    --     title = "Basic Commands",
    --     margin = 5,
    --     content = {
    --         { " Find File", "Telescope find_files", "<leader>ff" },
    --         { " Find Word", "Telescope live_grep", "<leader>lg" },
    --         { " Recent Files", "Telescope oldfiles", "<leader>of" },
    --         { "  File Explorer", "NvimTreeToggle", "<leader>ee" },
    --         { " Colorschemes", "Telescope colorscheme", "<leader>cs" },
    --     },
    --     highlight = "String",
    --     default_color = "",
    --     oldfiles_amount = 0,
    -- },

    options = {
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 3, 3, 0 },
    },
    colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
    },
    parts = { "header", "body"},
}
return settings